version: "3"
volumes: 
  postgres_data:
      driver: local
  mongodb_data:
      driver: local
services: 
  alpha-api: 
    build: 
      context: ./packages/api/alpha
    container_name: poc-alpha-api
    environment: 
      - PORT=7001
    expose: 
      - 7001
    ports: 
      - "7001:7001"
    tty: true
    depends_on:
      - mongodb
  alpha-ui: 
    build: 
      context: ./packages/ui/alpha
    container_name: poc-alpha-ui
    expose: 
      - 8001
    ports: 
      - "8001:80"
    tty: true
  beta-api: 
    build: 
      context: ./packages/api/beta
    container_name: poc-beta-api
    environment: 
      - PORT=7002
    expose: 
      - 7002
    ports: 
      - "7002:7002"
    tty: true
    depends_on:
      - mongodb
  beta-ui: 
    build: 
      context: ./packages/ui/beta
    container_name: poc-beta-ui
    expose: 
      - 8002
    ports: 
      - "8002:80"
    tty: true
  
  shell-api: 
    build: 
      context: ./packages/api/shell
    container_name: poc-shell-api
    environment: 
      - PORT=7000
    expose: 
      - 7000
    ports: 
      - 7000:7000
    tty: true
    depends_on:
      - mongodb
  shell-ui: 
    build: 
      context: ./packages/ui/shell
    container_name: poc-shell-ui
    expose: 
      - 8000
    ports: 
      - "8000:80"
    tty: true

  postgres:
      image: postgres
      container_name: poc-postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  mongodb:
      image: mongo:latest
      container_name: poc-mongodb
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
      ports:
        - 27017:27017
      volumes:
        - mongodb_data:/data/db
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      container_name: poc-keycloak
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
      volumes:
        - ./infra/keycloak:/tmp
      ports:
        - 8080:8080
      depends_on:
        - postgres
